#%RAML 1.0
title: Une API REST sur les contrevenants de la villes de Montréal
baseUri: http://127.0.0.1:5000/

/api:
  /nombre_amende_etablissement:
    /csv:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/csv:
                example:  |
                  Etablissement,Nombre
                  RESTAURANT BASHA,23

    /xml:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/xml:
                example:  |
                  <?xml version='1.0' encoding='utf-8'?>
                  <contrevenants>
                    <contrevenant>
                      <etablissement>RESTAURANT BASHA</etablissement>
                      <nombre>23</nombre>
                    </contrevenant>
                  </contrevenants>

    /json:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              application/json:
                example:  |
                  [
                    {
                      "etablissement": "RESTAURANT BASHA",
                      "nombre": 23
                    }
                  ]

    /interval:
      get:
        description: Extraire l'information des établissements avec l'interval des dates
        queryParameters:
          du:
            type: string
            description: Début pour le début de l'interval
            example: 2015-09-30
            required: true
          au:
            type: string
            description: Fin pour le début de l'interval
            example: 2015-10-05
            required: true
        responses:
            200:
              body:
                application/json:
                  example: |
                    [
                      {
                        "Adresse": "4219 Rue Notre-Dame Ouest ",
                        "Catégorie": "Restaurant",
                        "Date d'infraction": "2015-09-30",
                        "Date de jugement": "2017-03-16",
                        "Description": "Le lieu ou le véhicule doit être exempt de contaminants, de polluants, de toute espèce d'animaux y compris les insectes et les rongeurs ou de leurs excréments.",
                        "Montant de l'amende": 750,
                        "Propriétaire": "9313-2603 QUEBEC INC.  (Fermé)",
                        "Ville": "Montréal H4C 1R4",
                        "Établissement": "NOUVEAU RESTO MAK MAK"
                      }
                    ]

  /nouvelle_plainte:
    post:
      description: Déposer une plainte auprès de la ville contre un établissement
      queryParameters:
        etablissement:
          type: string
          description: Nom de l'établissement
          example: AILE BUFFALO BILL
          required: true
        no_civique:
          type: integer
          description: Numéro civique de l'adresse
          example: 4084
          required: true
        nom_rue:
          type: string
          description: Nom de la rue de l'adresse
          example: Rue Saint-Denis
          required: true
        ville:
          type: string
          description: Le nom de la ville et ainsi que le code postal
          example: Montréal H2W 2M5
          required: true
        date_visite:
          type: string
          description: Le moment ou la visite a eu lieu
          pattern: ^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])$
          example: 2018-05-28
          required: true
        prenom_plaignant:
          type: string
          description: Prénom de la personne qui a déposé une plainte
          example: Benoît
          required: true
        nom_plaignant:
          type: string
          description: Nom de la personne qui a déposé une plainte
          example: Mignault
          required: true
        description:
          type: string
          description: Une explication en quoi la plainte a été déposée
          example: Nous avons remarqué la présence de petits animaux dans la cuisine.
          required: true
      responses:
          201:
            body:
              application/json:
                example: |
                  [
                    {
                      "voici le numero de la plainte": 13
                    }
                  ]
  /plainte:
    /{id_plainte}:
      delete:
        description: Suppression d'une plainte ayant été déposée.
        responses:
          200:
            description: La plainte a bien été enlevé du système.
          404:
            description: La plainte n'existe pas dans notre système.
  /nouveau_profil:
    post:
      description: Création d'un nouveau profil d'utilisateur
      queryParameters:
        nom:
          type: string
          description: Nom du demandeur
          example: Mignault
          required: true
        prenom:
          type: string
          description: Prénom du demandeur
          example: Benoit
          required: true
        password:
          type: string
          description: Le password en clair qui sera ensuite sécurisé
          example: Patate123(((
          required: true
        courriel:
          type: string
          description: Le courriel du demandeur
          pattern: ^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$
          example: b.mignault@gmail.com
          required: true
        liste_etablissement:
          type: array
          description: La liste des établissement que l'utilisateur veut surveiller
          example: |
            [
              [
                "PIZZA EXPRESSO",
                "ALIMENTS MARINA"
              ]
            ]
          minItems: 1
          required: true
          uniqueItems: true
      responses:
          201:
            body:
              application/json:
                example: |
                  [
                    {
                      "Création du nouveau profil": "Succès !"
                    }
                  ]

