#%RAML 1.0
title: Une API REST sur les contrevenants de la villes de Montréal
baseUri: http://127.0.0.1:5000/

/api:
  /nombre_amende_etablissement:
    /csv:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/csv:
                example:  |
                  Etablissement,Nombre
                  RESTAURANT BASHA,23

    /xml:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/xml:
                example:  |
                  <?xml version='1.0' encoding='utf-8'?>
                  <contrevenants>
                    <contrevenant>
                      <etablissement>RESTAURANT BASHA</etablissement>
                      <nombre>23</nombre>
                    </contrevenant>
                  </contrevenants>
    /json:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              application/json:
                example:  |
                  [
                    {
                      "etablissement": "RESTAURANT BASHA",
                      "nombre": 23
                    }
                  ]
