#%RAML 1.0
title: Une API REST sur les contrevenants de la villes de Montréal
baseUri: http://127.0.0.1:5000/

/api:
  /nombre_amende_etablissement:
    /csv:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/csv:
                example:  |
                  Etablissement,Nombre
                  RESTAURANT BASHA,23

    /xml:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              text/xml:
                example:  |
                  <?xml version='1.0' encoding='utf-8'?>
                  <contrevenants>
                    <contrevenant>
                      <etablissement>RESTAURANT BASHA</etablissement>
                      <nombre>23</nombre>
                    </contrevenant>
                  </contrevenants>
    /json:
      get:
        description: Extraire l'information des établissements avec le nombre amende(s)
        responses:
          200:
            body:
              application/json:
                example:  |
                  [
                    {
                      "etablissement": "RESTAURANT BASHA",
                      "nombre": 23
                    }
                  ]
    get:
      description: Extraire l'information des établissements avec l'interval des dates
      queryParameters:
        du:
          type: string
          description: Début pour le début de l'interval
          example: 2015-09-30
          required: true
        au:
          type: string
          description: Fin pour le début de l'interval
          example: 2015-10-05
          required: true
      responses:
          200:
            body:
              application/json:
                example:  |
                    [
                      {
                        "Adresse": "4219 Rue Notre-Dame Ouest ",
                        "Catégorie": "Restaurant",
                        "Date d'infraction": "2015-09-30",
                        "Date de jugement": "2017-03-16",
                        "Description": "Le lieu ou le véhicule doit être exempt de contaminants, de polluants, de toute espèce d'animaux y compris les insectes et les rongeurs ou de leurs excréments.",
                        "Montant de l'amende": 750,
                        "Propriétaire": "9313-2603 QUEBEC INC.  (Fermé)",
                        "Ville": "Montréal H4C 1R4",
                        "Établissement": "NOUVEAU RESTO MAK MAK"
                      }
                    ]
